//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP2025_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class заказ_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public заказ_()
        {
            this.подробности_заказа_ = new HashSet<подробности_заказа_>();
        }
    
        public int код { get; set; }
        public Nullable<int> код_пользователя { get; set; }
        public Nullable<int> статус_заказа { get; set; }
        public string время_выполнения { get; set; }
    
        public virtual пользователи_ пользователи_ { get; set; }
        public virtual статус_заказа_ статус_заказа_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<подробности_заказа_> подробности_заказа_ { get; set; }
    }
}
