//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP2025_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class история_входа_
    {
        public int код { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> дата { get; set; }
        public Nullable<int> код_пользователя { get; set; }
        public Nullable<int> статус_входа { get; set; }
    
        public virtual пользователи_ пользователи_ { get; set; }
        public virtual статус_входа_ статус_входа_ { get; set; }
    }
}
