//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP2025_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class пользователи_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public пользователи_()
        {
            this.заказ_ = new HashSet<заказ_>();
            this.история_входа_ = new HashSet<история_входа_>();
            this.подробности_заказа_анализатор_ = new HashSet<подробности_заказа_анализатор_>();
            this.работа_бухгалтера_ = new HashSet<работа_бухгалтера_>();
        }
    
        public int код { get; set; }
        public string наименование { get; set; }
        public string логин { get; set; }
        public string пароль { get; set; }
        public Nullable<System.DateTime> дата_рождения { get; set; }
        public string паспорт { get; set; }
        public string телефон { get; set; }
        public string электронная_почта { get; set; }
        public Nullable<int> код_страховой { get; set; }
        public string номер_полиса { get; set; }
        public Nullable<int> тип_страхового_полиса { get; set; }
        public Nullable<int> код_роли { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<заказ_> заказ_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<история_входа_> история_входа_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<подробности_заказа_анализатор_> подробности_заказа_анализатор_ { get; set; }
        public virtual роль_ роль_ { get; set; }
        public virtual страховая_компания_ страховая_компания_ { get; set; }
        public virtual тип_полиса_ тип_полиса_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<работа_бухгалтера_> работа_бухгалтера_ { get; set; }
    }
}
