//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP2025_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class подробности_заказа_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public подробности_заказа_()
        {
            this.подробности_заказа_анализатор_ = new HashSet<подробности_заказа_анализатор_>();
        }
    
        public int код { get; set; }
        public Nullable<int> код_заказа { get; set; }
        public Nullable<int> код_услуги { get; set; }
        public Nullable<int> статус_услуги { get; set; }
        public string дата_выполнения { get; set; }
    
        public virtual заказ_ заказ_ { get; set; }
        public virtual статус_услуги_ статус_услуги_ { get; set; }
        public virtual услуги_ услуги_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<подробности_заказа_анализатор_> подробности_заказа_анализатор_ { get; set; }
    }
}
