//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP2025_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class подробности_заказа_анализатор_
    {
        public int код { get; set; }
        public Nullable<int> код_подробности { get; set; }
        public Nullable<int> код_лаборанта { get; set; }
        public Nullable<int> код_анализатора { get; set; }
        public Nullable<System.DateTime> дата_поступления { get; set; }
        public string время_выполнения { get; set; }
        public string результат { get; set; }
    
        public virtual Анализатор_ Анализатор_ { get; set; }
        public virtual подробности_заказа_ подробности_заказа_ { get; set; }
        public virtual пользователи_ пользователи_ { get; set; }
        public bool isSelected { get; set; }
    }
}
