//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP2025_01
{
    using System;
    using System.Collections.Generic;
    
    public partial class страховая_компания_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public страховая_компания_()
        {
            this.пользователи_ = new HashSet<пользователи_>();
            this.работа_бухгалтера_ = new HashSet<работа_бухгалтера_>();
        }
    
        public int код { get; set; }
        public string наименование { get; set; }
        public string адрес { get; set; }
        public string ИНН { get; set; }
        public string БИК { get; set; }
        public string расчетный_счет { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<пользователи_> пользователи_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<работа_бухгалтера_> работа_бухгалтера_ { get; set; }
    }
}
